CREATE TABLE IF NOT EXISTS "VisitWorkflowControl" (
  "id" TEXT NOT NULL DEFAULT 'default',
  "supportDataEnabled" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "VisitWorkflowControl_pkey" PRIMARY KEY ("id")
);
